query placenames($island_code: String) {
	placenames(island_code: $island_code) {
		_id
		code
		island_id
		number
		names {
			name {
				mi
				en
				ascii
			}
			audio {
				start
				end
				speaker_id
				file
			}
		}
		places {
			_id
			name {
				en
				mi
				ascii
			}
			feature_id
		}
	}
}