version: '3.7'

services:
  website:
    container_name: caddy
    image: caddy
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    env_file:
      - .secrets.env
