query zone($code: String) {
	zone(code: $code) {
		_id
		number
		code
		name {
			en
			mi
		}
		audio {
			file
		}
		region_id
		part_id
		island_id
		maplink {
			map_id
			mapareas {
				shape
				coords
			}
		}
		areas {
			name {
				en
				mi
			}
		}
		gazetteer
		speaker_ids
		iwi_ids
		images {
			landscape
		}
	}
}
