#md \temp
#cd \Temp
#wget https://download.geofabrik.de/australia-oceania/new-zealand-latest.osm.pbf

#docker run -t --name nominatim -v C:\Temp:/src -v nominatim:/data/postgresdata mediagis/nominatim sh /app/init.sh /src/new-zealand-latest.osm.pbf postgresdata 4

#docker run --restart=always -p 6432:6432 -p 8080:8080 -d --name nominatim -v nominatim:/var/lib/postgresql/11/main mediagis/nominatim bash /app/start.sh

#docker exec nominatim chown postgres:postgres /var/lib/postgresql/11/main
#docker exec nominatim chmod 0750 /var/lib/postgresql/11/main

#docker restart nominatim

version: '3.7'

services:
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim
    restart: unless-stopped
    ports:
      - 6432:6432
      - 8080:8080
    volumes:
      - nominatim:/var/lib/postgresql/11/main
    command: ['nominatim', 'bash', '/app/start.sh']
